const brands = [
  'Aston Martin',
  'BMW',
  'Bentley',
  'Bugatti',
  'Cadillac',
  'Chrysler',
  'Ferrari',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Maserati',
  'Mercedes Benz',
  'Mini',
  'Polestar',
  'Porsche',
  'Rolls Royce',
  'Smart',
  'Tesla',
  'Toyota',
  'Volkswagen',
];
const models = [
  '911',
  'A4',
  'A8',
  'Accord',
  'Alpine',
  'Altima',
  'Aventador',
  'Beetle',
  'CTS',
  'CX-9',
  'Camaro',
  'Camry',
  'Challenger',
  'Charger',
  'Civic',
  'Colorado',
  'Corvette',
  'Cruze',
  'Durango',
  'El Camino',
  'Expedition',
  'Explorer',
  'F-150',
  'Fiesta',
  'Focus',
  'Fortwo',
  'Golf',
  'Grand Cherokee',
  'Impala',
  'Jetta',
  'Land Cruiser',
  'LeBaron',
  'Malibu',
  'Mercielago',
  'Model 3',
  'Model S',
  'Model T',
  'Model X',
  'Model Y',
  'PT Cruiser',
  'Prius',
  'Ranchero',
  'Roadster',
  'Silverado',
  'Spyder',
  'Taurus',
  'V90',
  'Volt',
  'Wrangler',
  'XC90',
];

export const generateName = () => {
  const brand = brands[Math.floor(Math.random() * brands.length)];
  const model = models[Math.floor(Math.random() * models.length)];
  return `${brand} ${model}`;
};
